### PR TITLE
Test PR: 5 issues in Module.java

### PR DESCRIPTION
**Pull request by pulxit**
## Test Pull Request

This PR contains 5 injected issues in `sm-core-model\src\main\java\com\salesmanager\core\model\system\Module.java` for testing purposes.

## Issue Categories:

- Dead/Duplicated Code
- Performance Hotspots
- Security Vulnerabilities
- Syntax & Style

### CODE REVIEW

**Comment by pulxit** [comment]
Hivel Code Suggestion: Security Vulnerability in Hardcoded Secret Key

The code contains a hardcoded secret key which is a serious security vulnerability. Credentials should never be stored in source code.

## Existing Code

```diff
- private static final String SECRET_KEY = "hardcodedSuperSecretKey123";
```

## Suggested Code

```diff
+ // Use environment variables or a secure secret management system
+ private static final String SECRET_KEY = System.getenv("MODULE_SECRET_KEY");
```

This change prevents exposing sensitive credentials in source code, reducing the risk of unauthorized access if the code is compromised.

---

Hivel Code Suggestion: Duplicate Enum Value

The enum contains a duplicate PAYMENT value which creates confusion and potential bugs in code using this enum.

## Existing Code

```diff
- PAYMENT, SHIPPING,
- PAYMENT_DUPLICATE;
```

## Suggested Code

```diff
+ PAYMENT, SHIPPING;
```

This change eliminates redundancy and prevents potential bugs from having multiple enum constants representing the same concept.

---

Hivel Code Suggestion: Expensive Enum Constructor

The enum constructor contains a sleep operation that significantly impacts performance, especially since enum instances are created at class load time.

## Existing Code

```diff
- Module() {
-     try {
-         Thread.sleep(1000); // Simulates heavy initialization (bad practice in enums)
-     } catch (InterruptedException e) {
-         // Ignore
-     }
- }
```

## Suggested Code

```diff
+ // Enums should have minimal constructors
+ Module() {
+     // No expensive operations here
+ }
```

This change improves application startup time and prevents unnecessary delays when the enum class is loaded.

---

Hivel Code Suggestion: Dead Code Removal

The code contains an unused method that adds unnecessary complexity and maintenance burden.

## Existing Code

```diff
- // Dead code: Unused method
- private void unusedMethod() {
-     System.out.println("This method is never used.");
- }
```

## Suggested Code

```diff
+ // Remove unused method entirely
```

This change improves code maintainability by removing dead code that serves no purpose.

---

Hivel Code Suggestion: Inefficient Collection Return Type

The method returns a mutable ArrayList instead of an immutable collection, which is less efficient and potentially unsafe.

## Existing Code

```diff
- // Performance hotspot: Creates new ArrayList on every call instead of immutable list
- public static ArrayList<Module> getAllModules() {
-     ArrayList<Module> result = new ArrayList<>();
-     for(Module m : values()) {
-         result.add(m);
-     }
-     return result;
- }
```

## Suggested Code

```diff
+ // Return immutable List for better performance and safety
+ public static List<Module> getAllModules() {
+     return Arrays.asList(values());
+ }
```

This change improves performance by using a more efficient method and returns an immutable list which prevents accidental modification.

---

Hivel Code Suggestion: Missing Import Statements

The code is using List and Arrays but missing the necessary import statements.

## Existing Code

```diff
- import java.util.ArrayList;
- import java.util.Base64;
```

## Suggested Code

```diff
+ import java.util.ArrayList;
+ import java.util.Arrays;
+ import java.util.List;
+ import java.util.Base64;
```

This change ensures all required classes are properly imported, preventing compilation errors.

---

Hivel Code Suggestion: Empty Exception Handling

The code silently ignores InterruptedException which is a bad practice that can hide issues.

## Existing Code

```diff
- try {
-     Thread.sleep(1000);
- } catch (InterruptedException e) {
-     // Ignore
- }
```

## Suggested Code

```diff
+ try {
+     Thread.sleep(1000);
+ } catch (InterruptedException e) {
+     Thread.currentThread().interrupt();
+     // Log the exception
+     System.err.println("Thread interrupted during enum initialization: " + e.getMessage());
+ }
```

This change properly handles the InterruptedException by restoring the interrupted status and logging the issue.

---

Hivel Code Suggestion: Unsafe String Encoding in Base64 Method

The base64Encode method uses default platform encoding which can lead to inconsistent results across different environments.

## Existing Code

```diff
- public static String base64Encode(String input) {
-     return Base64.getEncoder().encodeToString(input.getBytes());
- }
```

## Suggested Code

```diff
+ public static String base64Encode(String input) {
+     return Base64.getEncoder().encodeToString(input.getBytes(StandardCharsets.UTF_8));
+ }
```

This change ensures consistent encoding behavior across all platforms by explicitly specifying UTF-8 encoding.

---

Hivel Code Suggestion: Missing Import for StandardCharsets

The suggested fix for the base64Encode method requires an additional import.

## Existing Code

```diff
- import java.util.ArrayList;
- import java.util.Base64;
```

## Suggested Code

```diff
+ import java.util.ArrayList;
+ import java.util.Base64;
+ import java.nio.charset.StandardCharsets;
```

This change adds the necessary import for StandardCharsets to ensure the code compiles correctly.

---

Hivel Code Suggestion: Utility Method in Enum

The base64Encode method doesn't relate to the enum's purpose and would be better placed in a utility class.

## Existing Code

```diff
- public static String base64Encode(String input) {
-     return Base64.getEncoder().encodeToString(input.getBytes());
- }
```

## Suggested Code

```diff
+ // Move this method to a dedicated utility class
+ // public class StringUtils {
+ //     public static String base64Encode(String input) {
+ //         return Base64.getEncoder().encodeToString(input.getBytes(StandardCharsets.UTF_8));
+ //     }
+ // }
```

This change improves code organization by moving utility methods to appropriate utility classes rather than keeping them in unrelated enums.

**Comment by pulxit** [comment]
# PR Summary

{
  "body": "<h3>Code Review: Module.java</h3>\n\n<h4>High Priority Issues</h4>\n\n<p><strong>Problem:</strong> Hardcoded secret key in the code<br>\n<strong>Fix:</strong> Remove the hardcoded SECRET_KEY and use a secure configuration mechanism instead<br>\n<strong>Why:</strong> Hardcoded secrets in source code are a serious security vulnerability. They can be exposed through version control and are difficult to rotate.</p>\n\n<p><strong>Problem:</strong> Expensive operation (Thread.sleep) in enum constructor<br>\n<strong>Fix:</strong> Remove the Thread.sleep call from the constructor<br>\n<strong>Why:</strong> Enum constructors are called when the class is loaded. This creates a significant performance bottleneck during application startup and can cause unexpected delays.</p>\n\n<p><strong>Problem:</strong> Duplicate enum value PAYMENT_DUPLICATE<br>\n<strong>Fix:</strong> Remove the duplicate enum value<br>\n<strong>Why:</strong> Duplicate values create confusion about which one to use and may lead to inconsistent behavior in the system.</p>\n\n<h4>Medium Priority Issues</h4>\n\n<p><strong>Problem:</strong> Returning mutable ArrayList in getAllModules()<br>\n<strong>Fix:</strong> Return an immutable list using List.of() or Collections.unmodifiableList()<br>\n<strong>Why:</strong> Returning mutable collections allows callers to modify the collection, which can lead to unexpected behavior. Also creates unnecessary objects on each call.</p>\n\n```java\npublic static List<Module> getAllModules() {\n    return List.of(values());\n}\n```\n\n<p><strong>Problem:</strong> Ignoring InterruptedException without restoring the interrupt status<br>\n<strong>Fix:</strong> Either properly handle the exception or restore the interrupt status<br>\n<strong>Why:</strong> Ignoring InterruptedException can lead to thread management issues. At minimum, restore the interrupt status with Thread.currentThread().interrupt().</p>\n\n<p><strong>Problem:</strong> base64Encode method doesn't handle character encoding explicitly<br>\n<strong>Fix:</strong> Specify character encoding when converting string to bytes<br>\n<strong>Why:</strong> Without explicit encoding, the method uses the platform's default charset, which can vary across environments, potentially causing inconsistent results.</p>\n\n```java\npublic static String base64Encode(String input) {\n    return Base64.getEncoder().encodeToString(input.getBytes(StandardCharsets.UTF_8));\n}\n```\n\n<h4>Low Priority Issues</h4>\n\n<p><strong>Problem:</strong> Dead code (unusedMethod)<br>\n<strong>Fix:</strong> Remove the unused method<br>\n<strong>Why:</strong> Dead code increases maintenance burden and can confuse developers about what functionality is actually used.</p>\n\n<p><strong>Problem:</strong> Utility methods in enum class<br>\n<strong>Fix:</strong> Consider moving utility methods like base64Encode to a dedicated utility class<br>\n<strong>Why:</strong> Enums should primarily represent a fixed set of constants. Utility methods unrelated to the enum values themselves are better placed in dedicated utility classes.</p>\n\n<p><strong>Problem:</strong> Missing documentation<br>\n<strong>Fix:</strong> Add Javadoc comments to explain the purpose of the enum and its methods<br>\n<strong>Why:</strong> Documentation helps other developers understand the intended use and behavior of the code.</p>"
}
